name: 'WordPress Theme Check Action'
description: 'Runs the Theme Check plugin against your theme'
author: 'The WordPress Contributors'
inputs:
  root-folder:
    description: 'The location of your theme'
    default: ./
branding:
  icon: 'clipboard'  
  color: 'blue'
runs:
  using: 'composite'
  steps: 
    - name: Copy host folder
      run: rsync -av --exclude=.git* ${{ inputs.root-folder }} ${{ github.action_path }}/test-theme
      shell: bash
    - name: Set path to action
      run: echo "::add-path::${{ github.action_path }}"
      shell: bash
    - name: Install
      run: npm install && npm run wp-env start
      shell: bash
    - name: Run Theme Check
      run: npm run wp-env run cli eval-file ./config/check-theme.php
      shell: bash
      