name: 'Test your theme'
description: 'Fill this in'
runs:
  using: "composite"
  steps: 
    - run: echo ${{ github.action_path }}
      shell: bash
    - run: ${{ github.action_path }} npm run wp-env start
      shell: bash