name: 'Test your theme'
description: 'Fill this in'
branding:
  icon: 'clipboard'  
  color: 'blue'
runs:
  using: "composite"
  steps: 
    - name: Copy host folder to action
      run: rsync -av --exclude=.git* ./ ${{ github.action_path }}/test-theme
      shell: bash
    - name: Install & run test
      run: cd ${{ github.action_path }} && npm install && npm run wp-env start && npm run wp-env run cli eval-file ./config/check-theme.php
      shell: bash
      