name: 'WordPress Theme Check Action'
description: 'Runs the Theme Check plugin against your theme'
author: 'The WordPress Contributors'
inputs:
  root-folder:
    description: 'The location of your theme'
    default: ./
branding:
  icon: 'clipboard'  
  color: 'blue'
runs:
  using: 'composite'
  steps: 
    - name: Copy host folder
      run: rsync -av --exclude=.git* ${{ inputs.root-folder }} ${{ github.action_path }}/test-theme
      shell: bash

    - name: List thing
      run:  ls
      shell: bash

      ## Run unit tests to test that the correct files exist.
      ## If these files don't exist, the environment won't start up
    - name: Run Theme Structure Test
      run: cd ${{ github.action_path }} && npm run check:structure
      shell: bash

      ## The following tests require an environment
      ## Start the environment
    - name: Install
      run: cd ${{ github.action_path }} && npm run install:environment
      shell: bash

      ## Run checks using theme-check plugin
    - name: Run Theme Check
      run: cd ${{ github.action_path }} && npm run check:theme-check
      shell: bash

      ## Run checks using e2e
    - name: Run JS Check
      run: cd ${{ github.action_path }} && npm run check:ui
      shell: bash
      