name: 'WordPress Theme Check Action'
description: 'Runs the Theme Check plugin against your theme'
author: 'The WordPress Contributors'
inputs:
  root-folder:
    description: 'The location of your theme'
    default: ./
branding:
  icon: 'clipboard'  
  color: 'blue'
runs:
  using: 'composite'
  steps: 
    - name: Copy host folder
      run: rsync -av --exclude=.git* ${{ inputs.root-folder }} ${{ github.action_path }}/test-theme
      shell: bash
    - name: Install
      run: cd ${{ github.action_path }} && npm install && npm run wp-env start && npm run activate-theme
      shell: bash
    # - name: Run Theme Check
    #   run: cd ${{ github.action_path }} && npm run theme-check
    #   shell: bash
    - name: Setup && Run JS Check
      run: cd ${{ github.action_path }}/actions/ui-check && npm install && npm run test:e2e
      shell: bash
      