name: 'Test your theme'
description: 'Fill this in'
runs:
  using: "composite"
  steps: 
    - run: echo ${{ toJSON( { "core": "WordPress/WordPress#5.5", "plugins": [ "https://downloads.wordpress.org/plugins/theme-check.zip" ], "mappings": { "config": "./config", "theme-to-test": "./" } } ) }} > .wp-env.json
    - run: ls
    - run: ${{ github.action_path }}/index.sh
      shell: bash